### ISSUE TITLE
Hamburger menu behaviour seems to be broken

### ISSUE THREAD

**Issue by kbwatts** [PolymerElements/app-layout-templates#2]
- Puts a shadow over the entire body even when not narrow
- Drawer is transparent when it shouldn't be

**Comment by frankiefu** [comment]
`paper-drawer-panel` and `paper-header-panel` have outdated tags.  Their #master branch work fine.  We will tag the release soon.

**Comment by kbwatts** [comment]
Thanks for that - great work!!
